"""member list indexes

Revision ID: 9836decf60fb
Revises: ca58d34004ac
Create Date: 2026-06-17 12:36:43.319284

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9836decf60fb'
down_revision: Union[str, Sequence[str], None] = 'ca58d34004ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The trigram GIN indexes below need the pg_trgm extension.
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_member_member_number_trgm',
        'member',
        ['member_number'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'member_number': 'gin_trgm_ops'},
    )
    op.create_index(
        'ix_user_email_trgm',
        'user',
        ['email'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'email': 'gin_trgm_ops'},
    )
    op.create_index(
        'ix_user_first_name_trgm',
        'user',
        ['first_name'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'first_name': 'gin_trgm_ops'},
    )
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(
        'ix_user_last_name_trgm',
        'user',
        ['last_name'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'last_name': 'gin_trgm_ops'},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_user_last_name_trgm',
        table_name='user',
        postgresql_using='gin',
        postgresql_ops={'last_name': 'gin_trgm_ops'},
    )
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(
        'ix_user_first_name_trgm',
        table_name='user',
        postgresql_using='gin',
        postgresql_ops={'first_name': 'gin_trgm_ops'},
    )
    op.drop_index(
        'ix_user_email_trgm', table_name='user', postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops'}
    )
    op.drop_index(
        'ix_member_member_number_trgm',
        table_name='member',
        postgresql_using='gin',
        postgresql_ops={'member_number': 'gin_trgm_ops'},
    )
    # ### end Alembic commands ###
