"""add member profile

Revision ID: ca58d34004ac
Revises: 0001
Create Date: 2026-06-17 10:39:56.914542

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

import app.common.fields

# revision identifiers, used by Alembic.
revision: str = 'ca58d34004ac'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'member',
        sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('whatsapp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('address_line_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('address_line_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('postcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('business_address_line_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('business_address_line_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('business_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('business_postcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('business_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('about', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('show_profile_publicly', sa.Boolean(), nullable=False),
        sa.Column('tuition_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('subject_specialisms', sa.JSON(), nullable=False),
        sa.Column('tuition_levels', sa.JSON(), nullable=False),
        sa.Column('qualification_levels', sa.JSON(), nullable=False),
        sa.Column('qualifications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('delivery_mode', sa.Enum('online', 'in_person', 'both', name='deliverymode'), nullable=True),
        sa.Column('code_of_practice_agreed', sa.Boolean(), nullable=False),
        sa.Column('code_of_practice_agreed_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('code_of_practice_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('contractual_rules_agreed', sa.Boolean(), nullable=False),
        sa.Column('contractual_rules_agreed_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('contractual_rules_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('dbs_policy_agreed', sa.Boolean(), nullable=False),
        sa.Column('dbs_policy_agreed_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('dbs_policy_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('privacy_policy_agreed', sa.Boolean(), nullable=False),
        sa.Column('privacy_policy_agreed_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('privacy_policy_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('level_eligibility_accepted', sa.Boolean(), nullable=False),
        sa.Column('level_eligibility_accepted_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('level_eligibility_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('cpd_platform_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('referral_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('verification_status', sa.Enum('processing', 'verified', name='verificationstatus'), nullable=True),
        sa.Column('safeguarding_completion_date', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('email_workflow_updates', sa.Boolean(), nullable=False),
        sa.Column('email_event_announcements', sa.Boolean(), nullable=False),
        sa.Column('email_blasts', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('member_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('updated_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_member_created_dt'), 'member', ['created_dt'], unique=False)
    op.create_index(op.f('ix_member_member_number'), 'member', ['member_number'], unique=True)
    op.create_index(op.f('ix_member_user_id'), 'member', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_user_id'), table_name='member')
    op.drop_index(op.f('ix_member_member_number'), table_name='member')
    op.drop_index(op.f('ix_member_created_dt'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
