"""add member profile

Revision ID: 1f77f9bb4583
Revises: 0001
Create Date: 2026-06-17 13:43:29.689141

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

import app.common.fields

# revision identifiers, used by Alembic.
revision: str = '1f77f9bb4583'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The trigram GIN indexes below need the pg_trgm extension.
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'member',
        sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('whatsapp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('address_line_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('address_line_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('postcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('about', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('tuition_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('subject_specialisms', sa.JSON(), nullable=False),
        sa.Column('tuition_levels', sa.JSON(), nullable=False),
        sa.Column('qualification_levels', sa.JSON(), nullable=False),
        sa.Column('qualifications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('delivery_mode', sa.Enum('online', 'in_person', 'both', name='deliverymode'), nullable=True),
        sa.Column('code_of_practice_agreed_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('contractual_rules_agreed_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('dbs_policy_agreed_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('privacy_policy_agreed_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('level_eligibility_accepted_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('referral_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('verification_status', sa.Enum('processing', 'verified', name='verificationstatus'), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('member_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.Column('updated_dt', app.common.fields.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_member_created_dt'), 'member', ['created_dt'], unique=False)
    op.create_index(op.f('ix_member_member_number'), 'member', ['member_number'], unique=True)
    op.create_index(
        'ix_member_member_number_trgm',
        'member',
        ['member_number'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'member_number': 'gin_trgm_ops'},
    )
    op.create_index(op.f('ix_member_user_id'), 'member', ['user_id'], unique=True)
    op.create_index(
        'ix_user_email_trgm',
        'user',
        ['email'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'email': 'gin_trgm_ops'},
    )
    op.create_index(
        'ix_user_first_name_trgm',
        'user',
        ['first_name'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'first_name': 'gin_trgm_ops'},
    )
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(
        'ix_user_last_name_trgm',
        'user',
        ['last_name'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'last_name': 'gin_trgm_ops'},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_user_last_name_trgm',
        table_name='user',
        postgresql_using='gin',
        postgresql_ops={'last_name': 'gin_trgm_ops'},
    )
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(
        'ix_user_first_name_trgm',
        table_name='user',
        postgresql_using='gin',
        postgresql_ops={'first_name': 'gin_trgm_ops'},
    )
    op.drop_index(
        'ix_user_email_trgm', table_name='user', postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops'}
    )
    op.drop_index(op.f('ix_member_user_id'), table_name='member')
    op.drop_index(
        'ix_member_member_number_trgm',
        table_name='member',
        postgresql_using='gin',
        postgresql_ops={'member_number': 'gin_trgm_ops'},
    )
    op.drop_index(op.f('ix_member_member_number'), table_name='member')
    op.drop_index(op.f('ix_member_created_dt'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
